language: node_js
node_js:
- '12'
deploy:
  provider: npm
  email:
    secure: hOXFugpmcpoKMWo/nSDPN0piwq4UEa0YhIcCzTW44giaeUUTL9H7Mz0Gz9dDT9tHum5Gc/n3mYvCMTC9juFrgu+pCEIrcWwApGnRVzGqzm9/d9uLlp4eG8l43tJpNzot1NhootUoWz6O4BHHKl/Gs91AMbGHf32Lf6gjcvv5LwZ5tQumgIBxqhTpq+6PoDNR2USN4RAzOGTxs6/trLDZFUbvpXGb51H1EmYsHSNJIczYpRXW1Q+9TIBoEErwl5DI3bx+3tE1b3MFhIEukJkwjZ6QtfBxeL5RPFi128Pcz0Uw2KWUbYz1Xzh9GcThHyW7xfjEem8lXO/ARygoqxzPHS80tLRJjiWf8nr7a/OX9L3DOYJPBWEn5EN8XUXZd507NpDj699pCWUt0EOYKaoM3QuGeO170vw8jHR8Sy2d0djUCwTqA18ww4hV9XapfNrFq92lu1rTFuDbvgHqormI279AhZdOJlaA76khl1H3Lv1+iikhtkfLRokd0LeqexSqDg0J1/9UoYX/sMVRo7sRT65FT075PasdTmW75pxenpXA2gQKeRHE03hfS5tTX8DEjpdq7+VU96nIdMt1V0XgAZGjhCEs3RDzE3FYhR1/SCIysWSkKH+5Zb8RA+oMDFQu2LX8HnN/5xWQtHaaVtLUkjTwNN5E637UBLXp/tQpl1M=
  api_key:
    secure: A8Unta4oq9DEo4Ss0uuF1FGrkHmCYcFeootiH0JisoOWBuWclDmv9J7KLFuoYbyVYmv2YwMM8upLpJB6uh4+3TcV6lh9ERd+ZgyTX4XXYJq3yc0mEKAB5TMFpWOKvUel2sETuc4OkOKN7fCNbp1Z8zK5DYmaFf6tZzLHtda8KD0wDGYKd4PbZnk+4JHFmn15lTyboYG0+chm0QcuBGY6Ct84Dqr3ESIX2m45eo1k9rLP8f1H9NTy5fzbZjXUtME1MoWKvG6pmF6E3PwsBETkPWYgOl/Bi80wL/8PQlUSMzanzA0kPAb+1E2aGq8LtO4quTaDx0a7mjNb2cH+B9z6in2FRaviJY10JtFWgcYjSymRhs/iOF6NOL84GZTpj97yTb7mI3bdSq9paBN4XkFbnk2ETYUnoJahpQgWJ5mwtyUplhLCAmN0Yp1fnwceebouYjILK4vjwe3ilVim0ewNieM4krYrsJxvEqlAoOt90xbK6MvFHtVurWPzK6N+OfMIpoU4FafJ5qiS6VEzjnkQTfzfCFmcRSHfkuuynEWT+eobrSBrJr7aDbue18WfvWXekXbF78frpFPOXeQBvtyw0qryHkYH/jW4dEMCaYry5ghlOR0+PdB/g6vAXi4lpGmbEx6AEgzEcN28Eu91H2LGXoVirpTgudNNEgKe3iDu9B4=
  on:
    branch: master
    tags: true
